version: '3.8'

services:
  backend:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    volumes:
      - ./model:/model
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://127.0.0.1:8001/api/v1/predict